# Copyright (C) 2025 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Clone sv-timestamp-analysis
  git:
    repo: https://github.com/ycongal-smile/sv-timestamp-analysis.git
    version: yco/stream_index_id
    dest: ../sv-timestamp-analysis
